name: python_cache
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: step2
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}

      - name: Done
        run:  echo Done
